import localFont from "next/font/local";
import "./globals.css";
// import Navbar from "./navbar/page";
import { NavbarDark } from "@/views/Navbar";
import { GoogleOAuthProvider } from "@react-oauth/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProvider clientId="220935764451-avbcui2oumkkqgmv144265onii98n6v6.apps.googleusercontent.com">
          {/* <NavbarDark /> */}
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
